[package]
name = "jvmrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.0.26", features = ["derive"]}
anyhow="1.0.66"
zip = "0.6.3"
tracing = "0.1"
tracing-subscriber = "0.3"