pub mod base;
pub mod loads;
pub mod constants;
pub mod control;
pub mod comparisons;
pub mod conversions;
pub mod extended;
pub mod stores;
pub mod math;
pub mod stack;
pub mod factory;
// pub mod invoke;
pub mod return_inst;
pub mod references;